// Generated by scripts/gen-whois-availability.mjs — do not edit by hand.
// IANA TLD list: # Version 2026062302, Last Updated Wed Jun 24 07:07:01 2026 UTC
// RDAP bootstrap publication: 2026-07-14T22:00:03Z
//
// Only TLDs that IANA leaves without a `whois:` value appear here. IANA stays
// authoritative: consult this table only after IANA discovery comes back empty.

/** What a TLD offers when the IANA root database lists no WHOIS server. */
export type WhoisAvailability =
  /** A port-43 server IANA does not advertise. */
  | { kind: "server"; host: string }
  /** The registry publishes no WHOIS at all — permanent, do not retry. */
  | { kind: "none" }
  /** WHOIS exists only as a web form; there is nothing to query on port 43. */
  | { kind: "web"; url: string };

export const WHOIS_AVAILABILITY: Readonly<Record<string, WhoisAvailability>> = {
  al: { kind: "none" },
  ao: { kind: "web", url: "https://www.dns.ao/ao/whois/" },
  aq: { kind: "none" },
  az: { kind: "web", url: "https://whois.az/" },
  ba: { kind: "web", url: "https://nic.ba/" },
  bb: { kind: "web", url: "https://whois.telecoms.gov.bb/" },
  bd: { kind: "web", url: "https://bdia.btcl.com.bd/" },
  bs: { kind: "none" },
  bt: { kind: "web", url: "http://www.nic.bt/" },
  bv: { kind: "none" },
  bz: { kind: "server", host: "whois.identitydigital.services" },
  cd: { kind: "server", host: "whois.nic.cd" },
  cg: { kind: "none" },
  ck: { kind: "none" },
  cu: { kind: "web", url: "https://www.nic.cu/" },
  cw: { kind: "none" },
  cy: { kind: "web", url: "https://www.nic.cy/cy-ui/home" },
  dj: { kind: "none" },
  eg: { kind: "none" },
  er: { kind: "none" },
  et: { kind: "none" },
  fk: { kind: "none" },
  ga: { kind: "server", host: "whois.nic.ga" },
  gb: { kind: "none" },
  gm: { kind: "web", url: "http://www.nic.gm/htmlpages/whois.htm" },
  gr: { kind: "web", url: "https://grweb.ics.forth.gr/public/whois?lang=en" },
  gt: { kind: "web", url: "https://www.gt/sitio/?lang=en" },
  gu: { kind: "none" },
  gw: { kind: "web", url: "https://registar.nic.gw/en/whois/" },
  jm: { kind: "none" },
  jo: { kind: "web", url: "https://www.domain.jo/FirstPageen.aspx" },
  kh: { kind: "none" },
  km: { kind: "none" },
  kp: { kind: "none" },
  kw: { kind: "server", host: "whois.nic.kw" },
  lc: { kind: "server", host: "whois.identitydigital.services" },
  lk: { kind: "server", host: "whois.nic.lk" },
  lr: { kind: "none" },
  mh: { kind: "none" },
  mil: { kind: "none" },
  mp: { kind: "none" },
  mt: { kind: "server", host: "whois.nic.org.mt" },
  mv: { kind: "none" },
  ne: { kind: "none" },
  ni: { kind: "web", url: "https://www.nic.ni/" },
  np: { kind: "web", url: "https://register.com.np/whois-lookup" },
  nr: { kind: "web", url: "https://www.cenpac.net.nr/dns/whois.html" },
  pa: { kind: "web", url: "http://www.nic.pa/en" },
  ph: { kind: "web", url: "https://whois.dot.ph/" },
  ps: { kind: "server", host: "whois.registry.ps" },
  py: { kind: "web", url: "https://www.nic.py/consultdompy.php" },
  sj: { kind: "none" },
  sl: { kind: "server", host: "whois.nic.sl" },
  sv: { kind: "web", url: "https://svnet.sv/" },
  sz: { kind: "none" },
  tj: { kind: "web", url: "http://www.nic.tj/whois.html" },
  tt: { kind: "web", url: "https://www.nic.tt/cgi-bin/search.pl" },
  va: { kind: "none" },
  vn: { kind: "web", url: "http://www.vnnic.vn/en" },
  "xn--54b7fta0cc": { kind: "web", url: "https://bdia.btcl.com.bd/" },
  "xn--fzc2c9e2c": { kind: "server", host: "whois.nic.lk" },
  "xn--mgbai9azgqp6j": { kind: "none" },
  "xn--mgbayh7gpa": { kind: "web", url: "https://www.domain.jo/FirstPageen.aspx" },
  "xn--mgbc0a9azcg": { kind: "none" },
  "xn--mgbcpq6gpa1a": { kind: "none" },
  "xn--mgbpl2fh": { kind: "none" },
  "xn--node": { kind: "web", url: "http://რეგისტრაცია.გე/" },
  "xn--qxam": { kind: "web", url: "https://grweb.ics.forth.gr/public/whois?lang=en" },
  "xn--wgbh1c": { kind: "server", host: "whois.dotmasr.eg" },
  "xn--xkc2al3hye2a": { kind: "server", host: "whois.nic.lk" },
  za: { kind: "server", host: "whois.nic.za" },
  zw: { kind: "none" },
};

/** The fallback entry for a TLD, or undefined when nothing is known about it. */
export function whoisAvailabilityForTld(tld: string): WhoisAvailability | undefined {
  return WHOIS_AVAILABILITY[tld.toLowerCase()];
}
